# Site wide configuration

title: Stuff
description: Writings that could possibly be worth reading.
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://blog.jfrey.info

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap

# default options
defaults:
  -
    values:
      toc: false
  -
    scope:
      type: posts
    values:
      layout: article

# Site owner
owner:
  name: Jérémy Frey
  email: 
  twitter: jfrey_xx
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
